name: Build

on:
  - push
  - pull_request

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Run Install
        run: pnpm i --frozen-lockfile
      - name: Build
        run: pnpm build
